import { useMemo } from 'react';
import type { InsightType } from '../../types';
import { insights, chartData } from '../../data';
import { Tag } from '../../components/ui/Tag';
import { AskBar } from '../../components/dora/AskBar';
import { FollowupCard } from '../../components/dora/FollowupCard';
import { InsightChart } from '../../components/charts/InsightChart';

export function InsightPage({type,selected,onType,onSelect,onTrace,onRoute,onNotice}:{type:InsightType;selected:number;onType:(t:InsightType)=>void;onSelect:(i:number)=>void;onTrace:(id:string)=>void;onRoute:(type:InsightType,id:string)=>void;onNotice:(m:string)=>void}){
 const list=insights[type];const x=list[selected]??list[0];const tone=x.type==='problem'?'red':x.type==='opportunity'?'green':'blue';
 const next:Record<string,string[]>={p1:['核对供应商 B 最近 30 天采购价与合同价差','按 A 产品线拆分毛利影响，确认 ¥230,000 影响区间','进入行动回路，发起采购议价并连续 7 天跟踪利润率'],p2:['提取门店 08 / 16 的退货商品、原因与批次','对比两家门店与其他门店的客服、物流和商品质量数据','先处理高频退货原因，再观察退货率是否回落至 3.2% 以下'],p3:['拆分订单、客单价和商品结构，确认增长是否由少数大单贡献','核查高价值订单的客户、渠道和商品组合是否可持续','设置订单量与客单价联动观察，避免销售额增长掩盖订单风险'],o1:['拆解新品系列对客单价增长的贡献，并区分价格与销量因素','筛选高客单门店复用的商品组合、陈列和销售动作','选择 3 家相似门店做两周小范围验证，再扩大推广'],o2:['对比华东 Top 10 门店的商品、会员和导购经营特征','提炼 7 家高客单门店的共同动作并评估复制成本','选 2 家普通门店开展复制试点，以客单价和转化率验收'],c1:['继续观察华东订单量 3 天，确认是否接近 -3% 升级阈值','同步检查客单价、流量和转化率，定位订单变化来源','若订单量跌破 -3%，自动升级为问题洞察并进入归因分析'],c2:['核对新增 327 条记录的数据完整性和重复率','确认刷新后的利润率、订单量、库存等核心指标是否异常','保留本次更新为数据事件，若触发阈值则生成对应洞察'],c3:['拆解新品销量增长来自哪些区域、门店和商品规格','核对增长门店的库存、补货和履约能力是否匹配','选择高潜门店复制新品经营动作，并设置周度增长目标'],c4:['核对当前 24% 指标的统计口径与历史基线是否一致','定位增长主要来自门店、客户还是商品结构变化','建立周度跟踪，连续两周稳定后再评估是否扩大经营动作']};
 const more=x.type==='problem'?'Dora 判断必须有数据依据，否则不升级。':x.type==='opportunity'?'机会判断关注“增长来源是否可复制”，而不是简单把上涨标成机会。':'变化判断关注“是否值得升级”，没有达到阈值时 Dora 不制造噪音。';
 const title=x.type==='problem'?'为什么值得处理？':x.type==='opportunity'?'为什么值得放大？':'为什么值得关注？';
 const cause1=x.type==='problem'?(x.id==='p2'?'门店 08 / 16':'A 产品线'):(x.type==='opportunity'?(x.id==='o1'?'新品系列':'华东门店'):(x.id==='c1'?'华东区域':'当前变化'));
 const cause2=x.type==='problem'?(x.id==='p2'?'两家门店':'供应商 B'):(x.type==='opportunity'?(x.id==='o1'?'高客单门店':'高价值画像'):(x.id==='c1'?'升级阈值':'新的经营信号'));
 const n1=x.type==='problem'?(x.id==='p2'?'+1.4pp':'+8.3%'):(x.type==='opportunity'?(x.id==='o1'?'62%':'70%'):(x.id==='c1'?'-1.8%':x.delta));
 let n2=x.type==='problem'?(x.id==='p2'?'4.6%':'+11.7%'):(x.type==='opportunity'?(x.id==='o1'?'¥2,998':'7 / 10'):(x.id==='c1'?'-3%':x.metric));
 if(x.id==='c2')n2='327';if(x.id==='c3')n2='2,460';if(x.id==='c4')n2='24%';
 return <section className="page active"><div className="head"><div><div className="eyebrow">INSIGHT · MULTI-LAYER</div><div className="h1">Dora 的业务洞察</div><p className="sub">总览只是入口；真正的判断发生在这里。不同洞察拥有不同的图表、证据和可信度，不共用一套“模板答案”。</p></div><button className="btn" onClick={()=>onNotice('已返回业务脉搏')}>← 返回业务脉搏</button></div>
  <div className="tabs">{(['problem','opportunity','change'] as InsightType[]).map(t=><button key={t} className={'tab '+(type===t?'active':'')} onClick={()=>onType(t)}>{t==='problem'?'问题洞察':t==='opportunity'?'机会洞察':'变化洞察'} · {insights[t].length}</button>)}</div>
  <div className="insight-shell"><div className="card insight-list"><div className="list-head"><b>{type==='problem'?'问题列表':type==='opportunity'?'机会列表':'变化列表'}</b><span>{type==='problem'?'按业务影响排序':type==='opportunity'?'按增长潜力排序':'按重要性排序'}</span></div>{list.map((item,i)=><button key={item.id} className={'insight-item '+(i===selected?'active':'')} aria-selected={i===selected} onClick={()=>onSelect(i)}><div className="itop"><Tag tone={item.type==='problem'?'red':item.type==='opportunity'?'green':'blue'}>{item.tag}</Tag><span className="confidence">置信 <b>{item.confidence}%</b></span></div><div className="iname">{item.title}</div><div className="idesc">{item.desc}</div><div className={'list-status '+(item.type==='change'?'watch':'none')}>{item.type==='change'?'变化先进入持续关注':'未加入行动回路'}</div></button>)}</div>
   <div className="card detail"><div className="detail-top"><div><Tag tone={tone}>{x.tag}</Tag><div className="detail-title">{x.title}</div><div className="detail-sub">{x.desc}</div></div><div className="detail-right"><Tag tone="ai">可信度 {x.confidence}%</Tag></div></div>
    <div className="chart-card card"><div className="chart-header"><span>{x.type==='problem'?'异常趋势':x.type==='opportunity'?'增长结构':'变化趋势'}</span><span className="muted">鼠标移动到图表区域查看具体数据</span></div><InsightChart data={chartData[x.id]}/></div>
    <div className="insight-route"><div className="route-node"><b>洞察页</b><p>{x.type==='change'?'先判断变化是否值得继续观察，并设置升级条件。':'先确认影响因素，再决定是否进入执行。'}</p></div><div className="route-arrow">→</div><div className="route-node"><b>{x.type==='change'?'持续关注':'行动回路'}</b><p>{x.type==='change'?'变化先进入持续关注，满足阈值后再升级为问题或机会。':'问题 / 机会直接进入行动回路，形成任务、验证和回写。'}</p></div></div>
    {x.type==='change'&&<div className="change-lifecycle"><h4>变化洞察的升级路径</h4><div className="level-row"><div className="level-badge watch">{x.id==='c2'?'数据事件':'观察中'}</div><div className="level-copy"><b>当前状态：</b>{x.id==='c2'?'数据更新已完成，先确认刷新是否带来新的经营变化。':'当前变化尚未达到升级阈值，先进入持续关注。'}</div></div><div className="level-row"><div className="level-badge op">机会升级</div><div className="level-copy"><b>满足条件：</b>正向变化稳定后，可升级为机会洞察并进入行动回路。</div></div><div className="level-row"><div className="level-badge problem">问题升级</div><div className="level-copy"><b>风险条件：</b>变化继续恶化并突破阈值后，升级为问题洞察，转入行动回路处理。</div></div><div className="logic-strip"><span className="logic-pill">持续关注</span><span className="logic-pill">阈值判断</span><span className="logic-pill">升级为问题 / 机会</span></div></div>}
    <div className="detail-bottom"><div className="panel"><h4>{title}</h4><div className="cause"><div className="cause-box hot"><div className="k">{x.type==='problem'?'主要因素':x.type==='opportunity'?'主要贡献':'当前变化'}</div><b>{cause1}</b><div className="n">{n1}</div></div><div className="arrow">→</div><div className="cause-box"><div className="k">进一步定位</div><b>{cause2}</b><div className="n">{n2}</div></div></div><div className="confidence-large"><div style={{display:'flex',justifyContent:'space-between'}}><span>为什么相信这次判断</span><b>{x.confidence}%</b></div><div className="cbar"><i style={{width:`${x.confidence}%`}}/></div><div style={{fontSize:12,color:'var(--muted)',marginTop:4}}>{x.source}</div></div><div className="evidence"><div><b>这条洞察有自己的依据</b><br/><span>{more}</span></div><button className="btn" onClick={()=>onTrace(x.id)}>打开证据链 →</button></div></div>
      <div className="panel next-panel"><h4>下一步建议</h4><div className="suggested">{(next[x.id]??[]).map((n,i)=><div key={n}><span>{i+1}</span>{n}</div>)}</div><FollowupCard title={x.title} question={x.question} onAsk={()=>onNotice(`Dora 已带入问题：“${x.question}”`)} onAction={()=>{onRoute(x.type,x.id);onNotice('已生成行动建议')}} footer={x.type==='change'?'这条变化先进入持续关注，达到阈值后会自动升级为问题或机会。':'这条洞察会生成行动回路，并在行动页形成可切换的任务。'}/></div>
    </div>
    <div className="main-buttons"><button className={`btn ${x.type==='opportunity'?'green':'primary'}`} onClick={()=>onRoute(x.type,x.id)}>{x.type==='change'?'加入持续关注 →':'加入行动回路 →'}</button><button className="btn" onClick={()=>onTrace(x.id)}>查看证据链 →</button></div>
   </div>
  </div><AskBar context={`${type==='problem'?'问题':type==='opportunity'?'机会':'变化'}洞察 · ${x.title}`} onSubmit={(q)=>onNotice(q?`Dora：已带入当前洞察上下文：“${q}”`:'可以直接输入一个业务问题。')} suggestions={[x.question,'哪些数据支持这个判断？']}/>
 </section>;
}
