import { useState } from 'react';
import { actionCases } from '../../data';
import type { ActionCase } from '../../types';
import { Tag } from '../../components/ui/Tag';
import { AskBar } from '../../components/dora/AskBar';

export function ActionPage({joined,onTrace,onNotice,onExecute,onAddExpert,onAddData}:{joined:string[];onTrace:(id:string)=>void;onNotice:(m:string)=>void;onExecute:(id:string)=>void;onAddExpert:()=>void;onAddData:()=>void}){
 const [current,setCurrent]=useState(joined[0]??'p1');const c:ActionCase=actionCases[current]??actionCases.p1;
 const list=joined.map(id=>actionCases[id]).filter(Boolean); const empty=!list.length;
 return <section className="page active"><div className="head"><div><div className="eyebrow">ACTION LOOP · CASE OBJECT</div><div className="h1">问题与机会的行动回路</div><p className="sub">从洞察加入的问题和机会都会在这里形成行动回路，可随时切换查看，直到验证完成或问题解决。</p></div><span className="status"><span className="dot"/> {c.code} · 推进中</span></div>
  <div className="action-switch"><span className="lbl">{empty?'已加入 · 0 项':'已加入 · 切换查看'}</span>{list.map(x=><button key={x.id} className={'action-tab '+(x.id===current?'active':'')} onClick={()=>setCurrent(x.id)}>{x.kind==='problem'?'问题':'机会'} · {x.caseTitle.split('·')[0].trim()}<span className="badge">{x.code}</span></button>)}</div>
  {empty?<div className="action-empty">还没有加入行动回路的问题或机会。前往「洞察」把问题或机会加入行动回路，这里才会出现对应的行动内容。</div>:<div className="action-layout"><div className="card action-card"><div className="problem-head"><Tag tone={c.tagCls}>{c.tag}</Tag><b>{c.caseTitle}</b><span className="pid">{c.source}</span></div><div className="action-evidence"><div className="ae-head"><b>数据链证据</b><button className="btn" onClick={()=>onTrace(c.id)}>打开证据链 →</button></div><div className="ae-meta"><span>门店经营数据.xlsx · 09:32 更新</span><span>{c.code} · 可追溯</span></div></div><div className="timeline"><Timeline title={c.steps[0].title} text={c.steps[0].desc} evidence={c.steps[0].evidence} done onTrace={()=>onTrace(c.id)}/><Timeline title={c.steps[1].title} text={c.steps[1].desc} evidence={c.steps[1].evidence} done onTrace={()=>onTrace(c.id)}/><Timeline title={c.current.title} text={c.current.desc} evidence={c.current.evidence} active onTrace={()=>onTrace(c.id)} currentWhy={c.current.why} onExecute={()=>onExecute(c.id)} onAsk={()=>onNotice('Dora：先验证最关键且最可干预的假设，因为这一步能最快降低不确定性。')}/><Timeline title={c.steps[2].title} text={c.steps[2].desc} evidence={c.steps[2].evidence} onTrace={()=>onTrace(c.id)}/><Timeline title={c.steps[3].title} text={c.steps[3].desc} evidence={c.steps[3].evidence} onTrace={()=>onTrace(c.id)}/></div></div><div className="card orch"><div className="orch-head"><h3>Dora 自动编排</h3><Tag tone="ai">系统已选 · 可增补</Tag></div><div className="orch-section"><div className="os-title"><span>专家团</span><button className="add-mini" onClick={onAddExpert}>+ 添加专家</button></div><div className="expert-chips">{c.experts.map(e=><span className="expert-chip" key={e}><i>👥</i>{e}<em>系统已选</em></span>)}</div></div><div className="orch-section"><div className="os-title"><span>数据</span><button className="add-mini" onClick={onAddData}>+ 添加数据</button></div><div className="data-chips">{c.data.map(d=><span className="data-chip" key={d}>{d}</span>)}</div></div><div className="orch-section"><div className="os-title"><span>技能 / 知识 / 工具</span></div><div className="orow"><div className="oi">✦</div><div><b>趋势 / 归因分析</b><p>{c.expertDesc}</p></div></div><div className="orow"><div className="oi">◎</div><div><b>零售经营指标口径</b><p>利润率目标与业务解释</p></div></div><div className="orow"><div className="oi">⌁</div><div><b>MCP · 业务数据查询</b><p>获取数据并生成分析结果</p></div></div></div><div className="archive"><b>{c.kind==='opportunity'?'机会档案':'问题档案'}</b><br/>{c.archive} 以后任何人接手，都能继续从同一上下文工作。</div></div></div>}
  <AskBar context={`${c.code} · ${c.caseTitle}`} onSubmit={(q)=>onNotice(q?`Dora：已带入 ${c.code} 上下文继续分析。`:'可以直接输入一个业务问题。')} suggestions={['为什么先做这一步？','如果验证失败下一步怎么办？']}/>
 </section>
}
function Timeline({title,text,evidence,onTrace,done,active,currentWhy,onExecute,onAsk}:{title:string;text:string;evidence:string;onTrace:()=>void;done?:boolean;active?:boolean;currentWhy?:string;onExecute?:()=>void;onAsk?:()=>void}){return <div className={'tl '+(done?'done ':'')+(active?'active':'')}><div className="tldot">{done?'✓':active?'●':'4'}</div><div className="tl-body"><div className="tl-head"><h4>{title}</h4><button className="step-trace" onClick={onTrace}>溯源 →</button></div><p>{text}</p>{active&&<div className="current"><b>为什么先做这一步？</b><p>{currentWhy}</p><div className="main-buttons"><button className="btn primary" onClick={onExecute}>立即执行</button><button className="btn" onClick={onAsk}>问 Dora 为什么</button></div></div>}<span className="step-evidence">{evidence}</span></div></div>}
