import { useState } from 'react';
import { watchItems } from '../../data';
import { AskBar } from '../../components/dora/AskBar';
import { Tag } from '../../components/ui/Tag';

export function WatchPage({onTrace,onNotice,onInsight}:{onTrace:(id:string)=>void;onNotice:(m:string)=>void;onInsight:(id:string)=>void}){
 const [input,setInput]=useState('帮我关注华东销售额，如果连续三天下降就提醒我');const [parsed,setParsed]=useState(false);const [freq,setFreq]=useState('每日 09:00');
 return <section className="page active"><div className="head"><div><div className="eyebrow">CONTINUOUS WATCH · DELEGATE</div><div className="h1">把业务目标交给 Dora，后面不用一直盯</div><p className="sub">持续关注不是预警配置页，而是“业务目标委托”。委托产生变化后，Dora 再把事件送回业务脉搏，并进入对应洞察。</p></div><span className="status"><span className="dot"/>6 个业务目标持续关注中</span></div>
  <div className="delegate"><div className="card delegate-main"><div className="delegate-kicker"><span>业务目标委托</span><span className="delegate-state">Dora 将持续检查</span></div><div className="d-title">用一句话托管一个业务目标</div><div className="d-sub">描述你要关注的指标、范围和触发条件，Dora 会理解意图并把变化送回业务脉搏。</div><label className="delegate-label" htmlFor="watchInput">告诉 Dora 你要关注什么</label><div className="input-line"><input id="watchInput" className="delegate-input" value={input} onChange={e=>setInput(e.target.value)}/><button className="btn primary" onClick={()=>{setParsed(true);onNotice('✓ Dora 已理解你的业务委托')}}>让 Dora 理解</button></div><div className="suggest-head">常用目标</div><div className="suggests">{['关注利润率','关注库存周转','关注华东销售','关注新品增长','关注退货率','关注大额订单'].map(s=><button className="suggest" key={s} onClick={()=>setInput(`帮我${s}`)}>{s}</button>)}</div><div className="delegate-freq"><span className="freq-lbl">检查频率</span>{['每日 09:00','数据更新时','实时','每周'].map(x=><button key={x} className={'freq-chip '+(freq===x?'active':'')} onClick={()=>setFreq(x)}>{x}</button>)}</div>{parsed&&<div className="delegate-result show"><b>✓ Dora 已理解你的业务委托</b><div className="intent-grid"><div className="k">业务目标</div><div>华东销售额</div><div className="k">指标口径</div><div>销售额 · 华东区域</div><div className="k">触发条件</div><div>连续 3 天下跌</div><div className="k">检查频率</div><div>{freq}</div><div className="k">升级路径</div><div>变化洞察 → 问题 / 机会</div><div className="k">主动反馈</div><div>数据变化 → 业务脉搏 → 变化洞察</div><div className="k">依据数据</div><div>门店经营数据.xlsx · 华东区域</div></div><div className="main-buttons"><button className="btn primary" onClick={()=>onNotice('✓ 已开始持续关注；后续变化会回到业务脉搏')}>开始持续关注</button><button className="btn" onClick={()=>document.getElementById('watchInput')?.focus()}>调整一下</button></div></div>}</div>
   <div className="card delegate-side"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><b style={{fontSize:15}}>Dora 接到委托后会做什么</b><Tag tone="ai">自动完成</Tag></div>{[['1','理解目标','识别指标、范围、周期和触发条件'],['2','选择数据与能力','自动匹配数据、知识、Skill 与工具'],['3','持续检查','异常、趋势、数据更新触发主动判断'],['4','回到业务脉络','形成事件并进入问题 / 机会 / 变化洞察']].map(([n,t,p])=><div className="mstep" key={n}><div className="mnum">{n}</div><div><b>{t}</b><p>{p}</p></div></div>)}</div>
  </div>
  <div className="card watch-table"><div className="whead"><div>业务目标</div><div>当前状态</div><div>关注逻辑</div><div>操作</div></div>{watchItems.map(w=><div className="wrow" key={w.id}><div><div className="wname">{w.name}</div><small>持续关注 · {w.source}</small></div><div className="wvalue"><Tag tone={w.color}>{w.value}</Tag></div><div className="wlogic">{w.logic}</div><button className="rowbtn" onClick={()=>{onTrace(w.id); if(w.id.startsWith('c')) onInsight(w.id)}}>查看</button></div>)}</div>
  <AskBar context="持续关注" onSubmit={(q)=>onNotice(q?`Dora：已带入持续关注上下文：“${q}”`:'可以直接输入一个业务问题。')} suggestions={['我正在关注哪些目标？','为什么还没触发？']}/>
 </section>;
}
