import { useState } from 'react';
import type { ReactNode } from 'react';
import type { ChartData } from '../../types';
const fmt=(v:number)=>Math.abs(v)>=1000?v.toLocaleString('en-US'):Number.isInteger(v)?String(v):Math.abs(v)<10?v.toFixed(1):v.toFixed(0);
export function InsightChart({data}:{data:ChartData}){
 const [hover,setHover]=useState<number|null>(null);
 const W=760,H=300,L=60,R=746,T=28,B=258,plotW=R-L,plotH=B-T;
 const bg=<rect key="bg" width={W} height={H} fill="#fbfcff"/>;
 let svg:ReactNode;
 if(data.kind==='bubble'){
  svg=<svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none">{bg}{data.bubbles.map((b,i)=>{const [cx,cy]=[[190,168],[390,140],[600,102]][i];return <g key={b.name} onMouseEnter={()=>setHover(i)}><circle cx={cx} cy={cy} r={b.size} fill={b.color} opacity=".9"/><text x={cx} y={cy-4} fill={b.color==='#665cf5'?'#fff':'#3f4656'} fontSize="15" fontWeight="800" textAnchor="middle">{b.count}</text><text x={cx} y={cy+18} fill={b.color==='#665cf5'?'#fff':'#5b6271'} fontSize="12" textAnchor="middle">{b.name}</text></g>})}<text x={L} y={B+24} fill="#9aa1b2" fontSize="11">气泡大小 = Top 高客单门店数量</text></svg>;
 } else if(data.kind==='step'){
  svg=<svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none">{bg}{data.steps.map((st,i)=>{const step=plotW/data.steps.length,cx=L+step*i+step/2,cy=T+plotH/2-26;return <g key={st.name} onMouseEnter={()=>setHover(i)}><circle cx={cx} cy={cy} r={st.done?16:14} fill={st.done?'#edf4ff':'#f8f9fc'} stroke={st.done?'#3975da':'#dfe4f0'} strokeWidth="2"/><text x={cx} y={cy+5} fill={st.done?'#2f66c4':'#9aa1b2'} fontSize="13" fontWeight="800" textAnchor="middle">{i+1}</text><text x={cx} y={cy+34} fill="#3f4656" fontSize="12" fontWeight="700" textAnchor="middle">{st.name}</text><text x={cx} y={cy+50} fill="#9aa1b2" fontSize="11" textAnchor="middle">{st.note}</text>{i<data.steps.length-1&&<line x1={cx+16} y1={cy} x2={L+step*(i+1)+step/2-16} y2={cy} stroke={st.done?'#3975da':'#dfe4f0'} strokeWidth="2"/>}</g>})}</svg>;
 } else if(data.kind==='bar'){
  const mx=Math.max(...data.series[0].values);svg=<svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none">{bg}{data.series[0].values.map((v,i)=>{const step=plotW/data.labels.length,bw=Math.min(84,step*.55),x=L+step*i+step/2-bw/2,y=B-(v/mx)*plotH*.9;return <g key={i} onMouseEnter={()=>setHover(i)}><rect x={x} y={y} width={bw} height={B-y} rx="6" fill={data.series[0].color} opacity={.45+i*.2}/><text x={x+bw/2} y={y-8} fill="#5149dc" fontSize="12" fontWeight="800" textAnchor="middle">{fmt(v)}{data.unit}</text><text x={L+step*i+step/2} y={B+24} fill="#9aa1b2" fontSize="11" textAnchor="middle">{data.labels[i]}</text></g>})}</svg>;
 } else if(data.kind==='barline'){
  const step=plotW/data.labels.length,bw=Math.min(82,step*.5),maxBar=Math.max(...data.bars.values),lmin=Math.min(...data.line.values)-6,lmax=Math.max(...data.line.values)+6,lys=(v:number)=>B-((v-lmin)/(lmax-lmin))*plotH*.8,linePts=data.line.values.map((v,i)=>[L+step*i+step/2,lys(v)] as const),path='M'+linePts.map(p=>p.join(',')).join(' L');
  svg=<svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none">{bg}{data.bars.values.map((v,i)=>{const x=L+step*i+step/2-bw/2,y=B-(v/maxBar)*plotH*.8;return <g key={i} onMouseEnter={()=>setHover(i)}><rect x={x} y={y} width={bw} height={B-y} rx="6" fill={data.bars.color} opacity={.45+i*.17}/><text x={x+bw/2} y={y-8} fill="#5149dc" fontSize="12" fontWeight="800" textAnchor="middle">¥{fmt(v)}</text><text x={L+step*i+step/2} y={B+24} fill="#9aa1b2" fontSize="11" textAnchor="middle">{data.labels[i]}</text></g>})}<path d={path} fill="none" stroke={data.line.color} strokeWidth="2.5" strokeLinecap="round"/>{linePts.map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r="3.5" fill="#fff" stroke={data.line.color} strokeWidth="2"/>)}</svg>;
 } else {
  const all=data.series.flatMap(s=>s.values),hasTh=data.kind==='line'&&data.threshold!==undefined,th=hasTh?data.threshold?.value:null;let mn=Math.min(...all,th??Infinity),mx=Math.max(...all,th??-Infinity),span=mx-mn||1;mn-=span*.15;mx+=span*.15;const xs=(i:number)=>L+i*plotW/(data.labels.length-1),ys=(v:number)=>B-((v-mn)/(mx-mn))*plotH;
  const grid=Array.from({length:6},(_,i)=>{const v=mn+(mx-mn)*i/5,y=B-plotH*i/5;return <g key={i}><line x1={L} y1={y} x2={R} y2={y} stroke={i===5?'#dfe3ea':'#eef0f4'}/><text x={L-10} y={y+4} fill="#9aa1b2" fontSize="11" textAnchor="end">{fmt(v)}{data.unit}</text></g>});
  svg=<svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none">{bg}{grid}{data.series.map(s=>{const pts=s.values.map((v,i)=>[xs(i),ys(v)] as const),d='M'+pts.map(p=>p.join(',')).join(' L');return <g key={s.name}><path d={d} fill="none" stroke={s.color} strokeWidth="2.5" strokeLinecap="round"/>{pts.map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r={hover===i?6:3.5} fill={hover===i?s.color:'#fff'} stroke={s.color} strokeWidth="2" onMouseEnter={()=>setHover(i)}/>)}</g>})}{hasTh&&data.threshold&&<><line x1={L} y1={ys(data.threshold.value)} x2={R} y2={ys(data.threshold.value)} stroke={data.threshold.color} strokeWidth="1.5" strokeDasharray="6 4"/><text x={R-6} y={ys(data.threshold.value)-6} fill={data.threshold.color} fontSize="11" textAnchor="end" fontWeight="700">{data.threshold.label}</text></>}{data.labels.map((l,i)=><text key={i} x={xs(i)} y={B+24} fill="#9aa1b2" fontSize="11" textAnchor="middle">{l}</text>)}</svg>;
 }
 let tip:string[]=[]; if(hover!==null){if(data.kind==='line')tip=[data.labels[hover],...data.series.map(s=>`${s.name}：${fmt(s.values[hover])}${data.unit}`)];else if(data.kind==='bar')tip=[data.labels[hover],`${data.series[0].name}：${fmt(data.series[0].values[hover])}${data.unit}`];else if(data.kind==='barline')tip=[data.labels[hover],`${data.bars.name}：¥${fmt(data.bars.values[hover])}`,`${data.line.name}：${data.line.values[hover]}%`];else if(data.kind==='bubble')tip=[data.bubbles[hover].name,`Top 门店：${data.bubbles[hover].count}`,`平均客单价：${data.bubbles[hover].value}`];else tip=[data.steps[hover].name,`${data.steps[hover].note} · ${data.steps[hover].done?'已完成':'等待中'}`]}
 return <div className="chart-area" onMouseLeave={()=>setHover(null)}>{svg}{hover!==null&&<div className="chart-tooltip show">{tip.map((x,i)=><div key={i} className={i===0?'tt-title':''}>{x}</div>)}</div>}</div>;
}
