import { useState } from 'react';
import type { InsightType, Page } from '../../types';
import { insights, autoExpertNotes, evidence, watchItems } from '../../data';
import { Tag } from '../../components/ui/Tag';
import { AskBar } from '../../components/dora/AskBar';

export function PulsePage({onPage,onInsight,onTrace,onNotice,dataLabel='门店经营数据.xlsx · 09:32 更新'}:{onPage:(p:Page)=>void;onInsight:(t:InsightType,idx?:number)=>void;onTrace:(id:string)=>void;onNotice:(m:string)=>void;dataLabel?:string}){
 const [problem,setProblem]=useState('p1');const [follow,setFollow]=useState(false);const [expert,setExpert]=useState('经营专家');
 const p=insights.problem.find(x=>x.id===problem)??insights.problem[0];
 const view:Record<string,{copy:string;target:string;facts:[string,string][]}>={p1:{copy:'8/31 起连续 3 天低于 18.5% 目标。Dora 判断这不是一次普通波动，当前主要影响来自 A 产品线的采购成本。',target:'目标 18.5%',facts:[['主要影响因素','A 产品线 · +8.3%'],['进一步定位','供应商 B · +11.7%']]},p2:{copy:'退货率从 3.2% 升至 4.6%，连续趋势主要集中在华东门店 08 / 16。',target:'区域基线 3.2%',facts:[['主要影响因素','门店 08 / 16'],['进一步定位','退货率 · +1.4pp']]},p3:{copy:'订单量下降 1.8%，但销售额增长 3.2%。Dora 将其列为问题，优先复核订单结构是否掩盖了需求走弱。',target:'销售额 ¥12.8M · ↑3.2%',facts:[['主要影响因素','订单量 · -1.8%'],['进一步定位','客单价 · ¥2,998']]}};
 const v=view[p.id];const pv=p.semantics?{copy:`${p.desc}；主要影响：${p.semantics.causeA.name} ${p.semantics.causeA.value}，进一步定位：${p.semantics.causeB.name} ${p.semantics.causeB.value}。`,target:v.target,facts:[['主要影响因素',`${p.semantics.causeA.name} · ${p.semantics.causeA.value}`],['进一步定位',`${p.semantics.causeB.name} · ${p.semantics.causeB.value}`]]}:v;
 return <section className="page active"><div className="head"><div><div className="eyebrow">BUSINESS PULSE · OVERVIEW</div><div className="h1">今天，有什么业务值得你关注？</div><p className="sub">数据更新后，Dora 自动完成“理解数据 → 判断重要性 → 形成业务脉络”。这里是总览入口，不在这里解决问题。</p></div><div className="status"><span className="dot"/>{dataLabel}</div></div>
  <div className="summary"><Summary label="需要处理" num={String(insights.problem.length)} cls="problem" desc="高影响问题 · 优先进入问题洞察" onClick={()=>onInsight('problem')}/><Summary label="增长机会" num={String(insights.opportunity.length)} cls="opportunity" desc="可放大机会 · 看增长来源" onClick={()=>onInsight('opportunity')}/><Summary label="重要变化" num={String(insights.change.length)} cls="change" desc="正在观察 · 看是否升级" onClick={()=>onInsight('change')}/><Summary label="持续关注" num={String(watchItems.length)} cls="watch" desc="Dora 正在替你持续检查" note="当前为静态展示，真实动态委托将在 V4 上线" onClick={()=>onPage('watch')}/></div>
  <div className="cockpit-kicker"><span>今日经营主线</span><span className="line"/><span>先判断优先级，再进入洞察</span></div>
  <div className="pulse-layout"><div className="card hero pulse-priority"><div className="priority-meta"><Tag tone="red">P1 · 需要处理</Tag><span className="priority-score">影响高 · 置信 {p.confidence}%</span></div><div className="priority-title">{p.title}</div><div className="priority-copy">{pv.copy}</div><div className="value-line"><span className="value">{p.metric}</span><span className={p.delta.startsWith('↑')?'delta-up':'down'}>{p.delta}</span><span className="muted">{pv.target}</span></div><div className="reason"><b>Dora 判断：</b>{p.semantics?`规则已定位：${pv.facts[0][1]} → ${pv.facts[1][1]}。进入行动回路前先验证该因素是否可干预。`:p.id==='p1'?'A 产品线采购成本上涨 8.3%，进一步定位到供应商 B，若趋势继续，本月预计利润影响约 ¥230,000。':p.id==='p2'?'退货上升主要来自少数门店与 SKU，不建议做全区域排查。':'订单量下降与客单价上升同时发生，需要先拆结构再判断风险。'}</div><div className="priority-evidence">{pv.facts.map(([k,val])=><div className="fact" key={k}><div className="k">{k}</div><div className="v">{val}</div></div>)}</div>
   <div className="problem-stack"><div className="problem-stack-head"><b>业务脉络 · 问题</b><span>3 条同级问题 · 可上下滑动查看</span></div><div className="problem-list">{insights.problem.map(x=><div key={x.id} className={'problem-item '+(x.id===problem?'active selected':'')}><button className="problem-toggle" onClick={()=>setProblem(problem===x.id?'':x.id)}><div className="meta"><b>{x.title}</b><div className="subline">{x.tag.replace('问题 · ','')} · 置信 {x.confidence}%</div></div><div className="arrow">{problem===x.id?'▾':'▸'}</div></button>{problem===x.id&&<div className="problem-body"><div className="body-row"><div className="desc">{x.desc}</div><button className="btn" onClick={()=>onInsight('problem',insights.problem.findIndex(i=>i.id===x.id))}>进入问题洞察 →</button></div><div className="mini"><Tag tone="red">{x.metric}</Tag><Tag>{x.delta}</Tag><Tag>{x.source}</Tag></div><div className="problem-evidence"><span>证据：{evidence[x.id]?.source} · {evidence[x.id]?.updated}</span><button className="btn" onClick={(e)=>{e.stopPropagation();onTrace(x.id)}}>证据链</button></div></div>}</div>)}</div></div>
   <div className="main-buttons"><button className="btn primary" onClick={()=>onInsight('problem',insights.problem.findIndex(i=>i.id===p.id))}>进入当前问题洞察 →</button><button className="btn soft" onClick={()=>{setFollow(!follow);onNotice(follow?'已取消跟进':'✓ 已加入持续跟进：利润率')}}>{follow?'已加入跟进 ✓':'让 Dora 帮我跟进'}</button><button className="btn" onClick={()=>onTrace(p.id)}>查看当前问题证据链</button></div>{follow&&<div className="followup-mini"><div className="ask-avatar">D</div><div className="followup-content"><div className="hint">Dora 已建立跟进</div><p>PRF-0831 · 每日检查利润率与供应商 B 价格，结果回写行动档案。</p></div><Tag tone="ai">自动监控</Tag></div>}</div>
   <div className="cockpit-side"><div className="card monitor-card"><div className="monitor-head"><h3>Dora 监控状态</h3><span className="monitor-count">6 个目标运行中</span></div><div className="monitor-stat"><div><b>09:32</b><span>最近一次数据检查</span></div><div><b>100%</b><span>关键判断可追溯</span></div></div><div className="monitor-list"><Monitor name="利润率" sub="目标线" status="已触发问题"/><Monitor name="华东销售额" sub="连续趋势" status="正常观察"/><Monitor name="客单价" sub="增长趋势" status="机会候选"/></div><button className="btn full" onClick={()=>onPage('watch')}>查看全部关注目标 →</button></div><div className="card monitor-card"><div className="monitor-head"><h3>本轮 Dora 工作</h3><Tag tone="ai">自动运行</Tag></div><Step done title="读取与清洗数据" sub="2,847 行 · 36 字段"/><Step done title="建立经营口径" sub="销售 / 利润 / 客单价 / 库存"/><Step active title="判断值得关注什么" sub="3 问题 · 2 机会 · 4 变化"/><div className="auto"><div className="auto-title">自动编排 · 专家团能力说明</div><div className="auto-tags">{Object.keys(autoExpertNotes).map(k=><button key={k} className={'auto-tag '+(expert===k?'active':'')} onClick={()=>{setExpert(k);onNotice(`已查看『${k}』能力说明`)}}>{k}</button>)}</div><div className="auto-note">{autoExpertNotes[expert]}</div></div></div></div></div>
   <div className="card signal-board"><div className="signal-board-head"><div><h3>其他经营信号</h3><p>这里承接主线之外的机会与变化，不与 P1 问题争夺视觉焦点。</p></div><div className="signal-tabs"><button className="signal-tab active">全部 6</button><button className="signal-tab" onClick={()=>onInsight('opportunity')}>机会 2</button><button className="signal-tab" onClick={()=>onInsight('change')}>变化 4</button></div></div><div className="signal-list"><Signal type="op" title="客单价连续 4 周增长" desc="新品系列贡献 62%，值得判断是否可复制。" value="¥2,998 · ↑5.1%" onClick={()=>onInsight('opportunity')}/><Signal type="op" title="华东高客单门店形成集群" desc="Top 10 中 7 家来自华东，可能存在共同经营动作。" value="7 / 10 · 70%" onClick={()=>onInsight('opportunity')}/><Signal type="ch" title="华东订单量下降 1.8%" desc="尚未达到 -3% 升级阈值，建议继续观察。" value="-1.8% · 3 天偏弱" onClick={()=>onInsight('change')}/><Signal type="ch" title="新品销量连续 3 周增长" desc="趋势明显，但尚未完成机会确认。" value="2,460 · ↑35.2%" onClick={()=>onInsight('change')}/></div></div>
   <AskBar context="门店经营总览" onSubmit={(q)=>onNotice(q?`Dora：已带入“${q}”并继续分析。`:'可以直接输入一个业务问题。')}/>
 </section>
}
function Summary(p:{label:string;num:string;cls:string;desc:string;onClick:()=>void;note?:string}){return <button className={`card summary-card ${p.cls}`} onClick={p.onClick}><div className="label">{p.label}{p.note?<span className="q" title={p.note}>?</span>:null}</div><div className="num">{p.num}</div><div className="desc">{p.desc}</div></button>}
function Monitor({name,sub,status}:{name:string;sub:string;status:string}){return <div className="monitor-item"><div><b>{name}</b><span> · {sub}</span></div><span>{status}</span></div>}
function Step({title,sub,done,active}:{title:string;sub:string;done?:boolean;active?:boolean}){return <div className={'step '+(done?'done ':'')+(active?'active':'')}><div className="step-icon">{done?'✓':'●'}</div><div><b>{title}</b><p>{sub}</p></div></div>}
function Signal({type,title,desc,value,onClick}:{type:'op'|'ch';title:string;desc:string;value:string;onClick:()=>void}){return <div className="signal-row"><div className={`signal-kind ${type}`}>{type==='op'?'增长机会':'重要变化'}</div><div className="signal-main"><b>{title}</b><p>{desc}</p></div><div className="signal-value"><span className="base">{value.split(' · ')[0]}</span><span className={`delta ${type==='op'?'pos':'neutral'}`}>{value.split(' · ')[1]}</span></div><button className="btn" onClick={onClick}>查看 →</button></div>}
